USE [Apeek]
GO
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMTP_HOST','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMTP_PORT','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMTP_USER','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMTP_PWD','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMTP_FROM','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMTP_FROM_NAME','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('EMAIL_CONTACTUS','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('EMAIL_ADMIN','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('IS_PRODUCTION','true')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('AWS_S3_BUCKET_NAME','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('AWS_S3_ACCESS_KEY','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('AWS_S3_SECRET_KEY','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('AWS_S3_PRE_SIGNED_URL_TIMEOUT','0')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('IMG_FILE_SERVER_URL','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMS_PROVIDER_LOGIN','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMS_PROVIDER_PWD','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMS_PROVIDER_LOGIN_ALT','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('SMS_PROVIDER_PWD_ALT','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_CLIENT_ID', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_CLIENT_SECRET', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_MODE','')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_CONNECTION_TIMEOUT', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_REQUEST_RETRIES', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_ACCOUNT1_API_USERNAME', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_ACCOUNT1_API_PASSWORD', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYMENT_TRANSACTION_COMMISION', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_ACCOUNT1_API_SIGNATURE', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_ACCOUNT1_API_APP_ID', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYPAL_EMAIL_ID', '')
INSERT INTO [dbo].[s_settings] ([key],[value]) VALUES('PAYMENT_TRANSACTION_CURRENCY', '')
GO


