using System;using System.Collections.Generic;using System.Linq;using System.Text;using System.Threading.Tasks;namespace Apeek.ViewModels.Models.Impl{
    public class AdminReportingVM    {        public DateTime StartRentalDate { get; set; }        public DateTime EndRentalDate { get; set; }        public string SharerId { get; set; }        public string BorrowerId { get; set; }        public int CategoryId { get; set; }        public string GoodNameId { get; set; }        public int AmountRangeId { get; set; }        public List<ProductsList> productsLists { get; set; }        public List<sharers> sharersLists { get; set; }        public List<CategoriesList> categoriesList { get; set; }        public List<Borrowers> borrowersList { get; set; }
        public List<ProductsList> productsListsAllData { get; set; }        public List<CategoriesList> categoriesListAllData { get; set; }

        public List<sharers> sharersListsAllData { get; set; }
        public List<Borrowers> borrowersListAllData { get; set; }

    }    public class SharedUsers
    {        public int UserId { get; set; }        public string Name { get; set; }    }    public class BorrowerUsers    {        public int UserId { get; set; }        public string Name { get; set; }    }    public class Categories    {        public int CategoryId { get; set; }        public string CategoryName { get; set; }    }    public class ProductsList : BaseCommon    {        public int GoodId { get; set; }        public string GoodName { get; set; }        public int CategoryId { get; set; }        public string CategoryName { get; set; }        public string GoodDescription { get; set; }        public double PricePerDay { get; set; }        public double PricePerWeek { get; set; }        public double Total { get; set; }        public string Month { get; set; }
        public int MonthId { get; set; }        public int year { get; set; }        public int Count { get; set; }        public DateTime CreatedDate { get; set; }    }


    public class BaseCommon    {        public bool UserStatus { get; set; }        public double SumTotal { get; set; }    }    public class CategoriesList    {        public int GoodId { get; set; }        public int CreatedBy { get; set; }        public string GoodName { get; set; }        public int CategoryId { get; set; }

        public string CategoryName { get; set; }        public string GoodDescription { get; set; }        public double PricePerDay { get; set; }        public double PricePerWeek { get; set; }        public double Total { get; set; }        public string Month { get; set; }        public int year { get; set; }        public int Count { get; set; }        public DateTime CreatedDate { get; set; }        public int UserId { get; set; }        public string FirstName { get; set; }        public string LastName { get; set; }        public string FullName { get; set; }    }    public class Borrowers    {        public int UserId { get; set; }        public string FirstName { get; set; }        public string LastName { get; set; }        public string FullName { get; set; }        public int GoodId { get; set; }        public int categoryId { get; set; }        public string GoodName { get; set; }        public double dayprice { get; set; }        public double weekprice { get; set; }        public DateTime GoodCreateddate { get; set; }        public string Month { get; set; }
        public int MonthId { get; set; }        public int year { get; set; }        public int Count { get; set; }        public DateTime CreatedDate { get; set; }    }    public class sharers    {        public int UserId { get; set; }        public string FirstName { get; set; }        public string LastName { get; set; }        public string FullName { get; set; }        public int GoodId { get; set; }        public int categoryId { get; set; }        public string GoodName { get; set; }        public double dayprice { get; set; }        public double weekprice { get; set; }        public string Month { get; set; }
        public int MonthId { get; set; }        public int year { get; set; }        public int Count { get; set; }        public DateTime CreatedDate { get; set; }    }}